package com.ssoplatform.idp.domain.mfa;

import java.security.SecureRandom;
import java.util.Objects;
import java.util.regex.Pattern;

/**
 * A plaintext, single-use e-mail OTP code: either the value randomly generated and e-mailed to the
 * user ({@link #generate()}), or a candidate typed back in by the user ({@link #of(String)}).
 * Deliberately a plain 6-digit numeric string, same shape as {@link TotpCode} - familiar UX for
 * users who may already be used to typing a 6-digit code from Phase 4.1's TOTP flow, and the
 * near-universal convention for e-mail/SMS OTP across real providers (GitHub, Google, AWS, ...).
 *
 * <p>Unlike {@link TotpCode} (only ever a candidate to verify, never generated by this
 * application itself - a real TOTP code is derived from the shared secret, not invented), this
 * type also generates fresh values: there is no secret to derive an e-mail OTP code from, so a
 * brand-new one must be created with a CSPRNG every time one is needed (see {@code
 * EnableEmailOtpUseCase}/{@code LoginUseCase}).
 */
public final class RawEmailOtpCode {

    private static final int DIGIT_COUNT = 6;
    private static final Pattern VALID_FORMAT = Pattern.compile("^[0-9]{6}$");
    private static final SecureRandom SECURE_RANDOM = new SecureRandom();

    private final String value;

    private RawEmailOtpCode(String value) {
        this.value = value;
    }

    /** Generates a brand-new, cryptographically random 6-digit code to hand out (e.g. by e-mail). */
    public static RawEmailOtpCode generate() {
        int upperBoundExclusive = (int) Math.pow(10, DIGIT_COUNT);
        int number = SECURE_RANDOM.nextInt(upperBoundExclusive);
        return new RawEmailOtpCode(String.format("%0" + DIGIT_COUNT + "d", number));
    }

    /** Wraps a code value received from an external caller (e.g. a confirm/challenge form field),
     * validating its shape before it's hashed and compared. */
    public static RawEmailOtpCode of(String candidate) {
        if (candidate == null || candidate.isBlank()) {
            throw new InvalidEmailOtpCodeException("Email OTP code must not be blank");
        }
        if (!VALID_FORMAT.matcher(candidate).matches()) {
            throw new InvalidEmailOtpCodeException("Email OTP code must be exactly 6 digits");
        }
        return new RawEmailOtpCode(candidate);
    }

    public String value() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RawEmailOtpCode that)) return false;
        return value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public String toString() {
        return "RawEmailOtpCode[REDACTED]";
    }
}
